// Define your own mock data here:
export const standard = () => ({
  notifications: [
    {
      id: 1,
      body: 'User 3 svaraði spurningu þinni',
      isSeen: false,
      questionId: 1,
      answerId: 1,
      answerCommentId: 0,
      userId: 1,
      createdAt: '2022-07-28T18:44:19.266Z',
    },
    {
      id: 2,
      body: 'User með id 4 gerði athugasemd við spurningu þína',
      isSeen: true,
      questionId: 0,
      answerId: 0,
      answerCommentId: 16,
      userId: 3,
      createdAt: '2022-07-28T20:05:17.932Z',
    },
    {
      id: 3,
      body: 'User með id 4 svaraði athugasemd þinni',
      isSeen: true,
      questionId: 0,
      answerId: 0,
      answerCommentId: 17,
      userId: 3,
      createdAt: '2022-07-28T20:05:31.966Z',
    },
    {
      id: 4,
      body: 'User með id 4 gerði athugasemd við svar þitt',
      isSeen: true,
      questionId: 2,
      answerId: 0,
      answerCommentId: 18,
      userId: 3,
      createdAt: '2022-07-28T20:05:57.565Z',
    },
    {
      id: 5,
      body: 'User með id 4 gerði athugasemd við spurningu þína',
      isSeen: true,
      questionId: 0,
      answerId: 0,
      answerCommentId: 19,
      userId: 3,
      createdAt: '2022-07-28T20:13:50.418Z',
    },
    {
      id: 6,
      body: 'User 4 svaraði spurningu þinni',
      isSeen: true,
      questionId: 2,
      answerId: 3,
      answerCommentId: 0,
      userId: 3,
      createdAt: '2022-07-28T20:14:08.937Z',
    },
    {
      id: 7,
      body: 'User með id 4 gerði athugasemd við svar þitt',
      isSeen: true,
      questionId: 2,
      answerId: 0,
      answerCommentId: 20,
      userId: 3,
      createdAt: '2022-07-28T20:15:14.606Z',
    },
  ],
})
