// Define your own mock data here:
export const standard = () => ({
  customAnswerComments: [
    {
      id: 0,
      body: 'Placeholder',
      userId: 0,
      parentId: null,
      answerId: 0,
      questionId: 0,
      createdAt: '2000-01-01T00:00:00.000Z',
      level: 0,
      rating: 0,
      isHidden: false,
    },
    {
      id: 2,
      body: 'athugasemd 1',
      userId: 3,
      parentId: 0,
      answerId: 1,
      questionId: 0,
      createdAt: '2022-07-28T18:44:30.202Z',
      level: 1,
      rating: 0,
      isHidden: false,
    },
    {
      id: 3,
      body: 'athugasemd',
      userId: 3,
      parentId: 0,
      answerId: 0,
      questionId: 1,
      createdAt: '2022-07-28T18:45:50.839Z',
      level: 1,
      rating: 0,
      isHidden: false,
    },
    {
      id: 4,
      body: 'athugasemd við spurningu',
      userId: 3,
      parentId: 0,
      answerId: 0,
      questionId: 1,
      createdAt: '2022-07-28T19:57:02.662Z',
      level: 1,
      rating: 0,
      isHidden: false,
    },
    {
      id: 5,
      body: 'athugasemd við spurningu',
      userId: 3,
      parentId: 0,
      answerId: 0,
      questionId: 1,
      createdAt: '2022-07-28T19:57:47.425Z',
      level: 1,
      rating: 0,
      isHidden: false,
    },
  ],
})
